name: Push to Ec2

# Trigger deployment only on push to master
on:
  push:
    branches: 
      - master


jobs:
  #deploy:
   # name: Deploy to EC2
   # runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install npm dependencies
        run: npm install
      - name: Run build 
        run: npm run build --if-present
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.UCHE_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}